---

- hosts: all
  become: yes
  tasks:

  - name: install apache and php package
    package: 
      name: 
        - " {{ apache_package }} "
        - " {{ php_package }} " 
      state: present
      update_cache: yes

