---

- hosts: all
  become: yes
  pre_tasks:

  - name: update cache (CentOS)
    tags: always
    yum: 
      update_cache: yes
    changed_when: false  
    when: ansible_distribution == "CentOS"

  - name: update cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false  
    when: ansible_distribution == "Ubuntu"

- hosts: multi
  become: yes
  roles:
    - base 

- hosts: workstations
  become: yes
  roles:
    - workstations      
     

- hosts: app
  become: yes 
  roles: 
    - web_servers 


- hosts: app
  become: yes
  roles:
    - db_servers

- hosts: workstations
  become: yes
  roles:
    - file_servers
    - ntp  
