---

- hosts: all
  become: yes
  pre_tasks:

  - name: install updates centos
    tags: always
    yum: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: centos
  become: yes  
  tasks:             

  - name: install apache and php package
    tags: apache,centos,httpd
    package: 
      name: 
        - httpd
        - php
      state: present
    when: ansible_distribution == "CentOS"


- hosts: app
  become: yes
  tasks: 
    - name: install mariadb (CentOS)
      tags: centos,db,mariadb
      yum:
        name: mariadb
        state: present
      when: ansible_distribution == "CentOS"  

    - name: install mariadb (Ubuntu)
      apt:
        name: mariadb-server
        state: present
      when: ansible_distribution == "Ubuntu"  

- hosts: centos
  become: yes
  tasks:
    - name: install samba package
      tags: samba
      package: 
        name: samba
        state: present
