- name: install apache and php package
  tags: apache,centos,httpd
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: present
  when: ansible_distribution == "CentOS"

- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: "{{ apache_service }}" 
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: change email adress for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^ServerAdmin"
    line: ServerAdmin somebody_else@somewhere.com
  when: ansible_distribution == "CentOS"
  notify: restart_apache


- name: copy default html for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
