- name: add ssh key for simone
  authorized_key:
    user: simone
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdyT84FWqHO1khP5pizzcJ6g0mi8yO5JpUPGrfX9aTTM2OfmpehMl7uuRXW+UA+/pkwXuSaYcw6DgWlf2qgg58eIsQG7HaWnp9rpkYrhvQqOUjHucq0HLIuCpugh35t9EC8NpXeG66A5KVQnWfxr8q1YKgfOvIW9UV64g6270XVI7msG+5cBvu/lmfQ7oEzaYeRCvebpa8xE4Ae5ivf3F3u5WlGmyBaeQST2eS7lfQ5UardFccsai1xM+QNv8Cx5NvqboY8gsbdbrRzU65UNSQHKL4GZ7i/sZsv2JkDiKI7rwcHmn3Syz6kho1XteUDrk3HfTFsUDFcBUtiFvcyo5QxMo3NZlZ8PA/DZBP/eCjo5KiOD1g+qJ3NHttfnkJlCjp8KjIC2MGfMjwKtNbpoiNVL8ee5Ay1m6bslx7rNZoDgu5L5Y6Xym0aV2Zahb+RWA6o+2ifr/Zw3xcsbNlAcToRlDkATN67rgsUNPLEdOR3fdsd9kkVMpZUpp75TZ4MC8= root@DESKTOP-33EJJ2S'

- name: generate sshd_config from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd  
